### ISSUE TITLE
[インフラ]外部インターネットからバックエンドサーバーへのアクセス制限

### ISSUE THREAD

**Issue by Nowe-melancholy** [exchange-wata/SweetheartSuite#100]
- 外部インターネットからバックエンドサーバーへのアクセスをNext.jsサーバーに限定することってできるんかな
- これができるならGoogleメアドかどうかの検証をNext.jsサーバーでやっちゃえばいいから、NATゲートウェイ使わなくてもいいのでは！？て思った

**Comment by exchange-wata** [comment]
どっちかっていうと逆かもしれない…>_<

awsリソース(今回だとecs)から外部インターネットに繋ぐために、NAT gatewayが必要って感じ！

BEからGoogle のAPI叩くのやめないと通信しなくてもいい、って状況にはならない気がした…！

**Comment by exchange-wata** [comment]
もしverecl?で完結できるならそれは助かる！！

**Comment by Nowe-melancholy** [comment]
元のissueに書いたこと色々端折りすぎてるんだけど、
- 現状BEはどこからでもリクエストを受け取れる
  - -> CreateUser, CreateTempUserの引数をメアドにすると、それがGoogle認証されたものか担保できない
  - -> だからGoogle id_tokenを引数にしてGoogle APIで検証してる
- BEのリクエスト元をNext.jsサーバーに限定できるなら
  - -> Next.jsでGoogle APIを使ってid_tokenの検証をして
  - -> 検証済みのGoogleメアドをBEにリクエストするっていう形にできる
  - -> BEからGoogle API叩かなくて良くなる！？

って感じ！！

**Comment by exchange-wata** [comment]
おー！なるほど！

**Comment by exchange-wata** [comment]
理解した！！！
