### ISSUE TITLE
ユースケース一覧

### ISSUE THREAD

**Issue by Nowe-melancholy** [exchange-wata/SweetheartSuite#14]
## 概要
- ユースケースを洗い出す
- 図とか作るのめんどいからテキストベース

## 一覧
- ユーザー作成
- ログイン
- #15 
- リスト作成
- やること作成
- etc

**Comment by exchange-wata** [comment]
画面の方も更新してみた！
https://github.com/exchange-wata/SweetheartSuite?tab=readme-ov-file#%E7%94%BB%E9%9D%A2%E8%A8%AD%E8%A8%88
