### ISSUE TITLE
ログインAPI

### ISSUE THREAD

**Issue by Nowe-melancholy** [exchange-wata/SweetheartSuite#21]
## 概要
- input
  - googleトークン: string
- output
  - DBにユーザーが存在 -> JWT
  - 存在しない -> null？
- 処理内容
  - googleトークン検証
    - 失敗 -> error
  - 成功したらDBに存在するかチェック

## 使い方
- ログイン画面で叩く
- JWT発行された -> そのままログイン
- null返ってきた -> サインアップ処理に進む

**Comment by exchange-wata** [comment]
JWT← { userId: hoge }を使う
