### ISSUE TITLE
リクエスト送信

### ISSUE THREAD

**Issue by exchange-wata** [exchange-wata/SweetheartSuite#23]
## 概要
- wikiは[こちら](https://github.com/exchange-wata/SweetheartSuite/wiki/%5B%E3%83%A6%E3%83%BC%E3%82%B9%E3%82%B1%E3%83%BC%E3%82%B9%5D%E3%82%AB%E3%83%83%E3%83%97%E3%83%AB%E6%88%90%E7%AB%8B)

## wikiの該当箇所
```
Aがログインする
相手（B）をメールアドレスで探す
メアドが存在 & 相手がカップル未成立ならリクエストを送れる
```

## API設計
- input
  - mailaddress
- output
  - 送信成功→true
  - メアドが存在しない or 送信失敗→エラー

**Comment by exchange-wata** [comment]
@Nowe-melancholy 
リクエスト送信のapi設計したので確認お願いします！
今のところ、実際に相手にメール送るとかではなく、画面上でリクエスト送信や受信有無の確認できるだけの想定してます。イメージあってますかね..？><

**Comment by Nowe-melancholy** [comment]
おっけーそう！
メール送るのは考えてないっす！（メール機構さえ作れれば簡単に追加できるだろうし）

**Comment by exchange-wata** [comment]
@Nowe-melancholy 
確認あざす！

リクエストの種類って以下であってますか？><
```
  const requestTypes = [
    { id: 1, name: '送信済み' },
    { id: 2, name: '承認' },
    { id: 3, name: '拒否' },
  ];
```

**Comment by Nowe-melancholy** [comment]
それで大丈夫だと思う！
