### ISSUE TITLE
カップル登録

### ISSUE THREAD

**Issue by exchange-wata** [exchange-wata/SweetheartSuite#24]
## 概要
- wikiは[こちら](https://github.com/exchange-wata/SweetheartSuite/wiki/%5B%E3%83%A6%E3%83%BC%E3%82%B9%E3%82%B1%E3%83%BC%E3%82%B9%5D%E3%82%AB%E3%83%83%E3%83%97%E3%83%AB%E6%88%90%E7%AB%8B)

## wiki該当箇所
```
Bがログインする
リクエストが来ていることを確認する
承認 or 拒否できる
承認したらカップル成立
拒否したらそこで終了
```

## API設計
- input
  - isAccepted(承認フラグ): true or false
- output
  - 承認→couple presenter
  - 拒否→null

**Comment by exchange-wata** [comment]
@Nowe-melancholy 
カップル登録のapi設計したので確認お願いします！

**Comment by Nowe-melancholy** [comment]
承認時の戻り値にcoupleIdさえあればたぶん大丈夫！
