### ISSUE TITLE
マージしたブランチ勝手に削除してほしい

### ISSUE THREAD

**Issue by Nowe-melancholy** [exchange-wata/SweetheartSuite#35]

**Comment by exchange-wata** [comment]
設定↓したので今度から消えるかもしれない
![スクリーンショット 2024-05-25 13 11 11](https://github.com/exchange-wata/SweetheartSuite/assets/36654133/565a1491-10f9-43d4-ad36-b5fe9532807a)

**Comment by Nowe-melancholy** [comment]
消えたの確認した！
