### ISSUE TITLE
モジュールごとにDBスキーマを分割したくなるかもしれない

### ISSUE THREAD

**Issue by Nowe-melancholy** [exchange-wata/SweetheartSuite#4]
# 概要
- モジュラモノリスで作る場合、DBが複数ある必要はないけど（トランザクションを分割する意味でも）モジュール単位でスキーマが分かれてたほうがいいかもしれない

# 参考
https://www.prisma.io/docs/orm/prisma-schema/data-model/multi-schema

**Comment by exchange-wata** [comment]
@Nowe-melancholy 
schema指定してTBL作れるように設定しているので、こちらcloseしても良いですか？？><
https://github.com/exchange-wata/SweetheartSuite/blob/eb3829c6586b2985fa6d5d09b64f8ab05c4374b3/backend/prisma/schema.prisma#L4

**Comment by Nowe-melancholy** [comment]
👍 👍 👍
